/* Func3Parser.java */
/* Generated By:JavaCC: Do not edit this line. Func3Parser.java */
package lf3.plp.functional3.parser;
import java.util.ArrayList;
import java.util.List;
//Imports da Funcional3
import lf3.plp.functional3.*;
import lf3.plp.functional3.expression.*;
import lf3.plp.functional3.declaration.DecComposta;
//Imports da Funcional2
import lf3.plp.functional2.declaration.DecFuncao;
import lf3.plp.functional2.expression.ValorFuncao;
import lf3.plp.functional2.expression.ExpDeclaracao;
import lf3.plp.functional2.expression.Aplicacao;
//Imports da Funcional1
import lf3.plp.functional1.declaration.DeclaracaoFuncional;
import lf3.plp.functional1.declaration.DecVariavel;
import lf3.plp.functional1.expression.IfThenElse;
//Imports da Express�o2
import lf3.plp.expressions2.expression.Expressao;
import lf3.plp.expressions2.expression.Valor;
import lf3.plp.expressions2.expression.ValorInteiro;
import lf3.plp.expressions2.expression.ValorString;
import lf3.plp.expressions2.expression.ValorBooleano;
import lf3.plp.expressions2.expression.Id;
import lf3.plp.expressions2.expression.ExpMenos;
import lf3.plp.expressions2.expression.ExpNot;
import lf3.plp.expressions2.expression.ExpLength;
import lf3.plp.expressions2.expression.ExpSoma;
import lf3.plp.expressions2.expression.ExpSub;
import lf3.plp.expressions2.expression.ExpAnd;
import lf3.plp.expressions2.expression.ExpOr;
import lf3.plp.expressions2.expression.ExpEquals;
import lf3.plp.expressions2.expression.ExpConcat;

public class Func3Parser implements Func3ParserConstants {
  public static void main(String args [])
  {
    Func3Parser parser;
    if (args.length == 0)
    {
      System.out.println("Funcional 3 PLP Parser Version 0.0.1:  Reading from standard input . . .");
      parser = new Func3Parser(System.in);
    }
    else if (args.length == 1)
    {
      System.out.println("Funcional 3 PLP Parser Version 0.0.1:  Reading from file " + args [0] + " . . .");
      try
      {
        parser = new Func3Parser(new java.io.FileInputStream(args [0]));
      }
      catch (java.io.FileNotFoundException e)
      {
        System.out.println("Funcional 3 PLP Parser Version 0.0.1:  File " + args [0] + " not found.");
        return;
      }
    }
    else
    {
      System.out.println("Funcional 3 PLP Parser Version 0.0.1:  Usage is one of:");
      System.out.println("         java Func3Parser < inputfile");
      System.out.println("OR");
      System.out.println("         java Func3Parser inputfile");
      return;
    }
    Programa programa = null;
    try
    {
      programa = parser.Input();

       if (!programa.checaTipo())
          {
            System.out.println("Funcional 3 PLP Parser Version 0.0.1: Encountered errors during parse.");
        System.exit(0);
      }

      System.out.println("Funcional 3 PLP Parser Version 0.0.1: Funcional3 program parsed successfully.");
    }
    catch (Exception e)
    {
      e.printStackTrace();
      System.out.println("Funcional 3 PLP Parser Version 0.0.1: Encountered errors during parse.");
      System.exit(0);
    }
    try
    {
      System.out.println("Funcional 3 PLP Parser Version 0.0.1: running...");
      Valor val = (Valor) programa.executar();
      if (val instanceof ValorString)
      {
        ValorString valStr = (ValorString) val;
        System.out.println("Funcional 3 PLP Parser Version 0.0.1: resultado=" + valStr.valor());
      }
      else if (val instanceof ValorInteiro)
      {
        ValorInteiro valInt = (ValorInteiro) val;
        System.out.println("Funcional 3 PLP Parser Version 0.0.1: resultado=" + valInt.valor());
      }
      else if (val instanceof ValorBooleano)
      {
        ValorBooleano valBool = (ValorBooleano) val;
        System.out.println("Funcional 3 PLP Parser Version 0.0.1: resultado=" + valBool.valor());
      }
      else if (val instanceof ValorFuncao)
      {
        ValorFuncao valFunc = (ValorFuncao) val;
        System.out.println("Funcional 3 PLP Parser Version 0.0.1: resultado = " + valFunc);
      }
       else if (val instanceof ValorLista)
      {
        ValorLista valLista = (ValorLista) val;
        System.out.println("Funcional 3 PLP Parser Version 0.0.1: resultado = " + valLista.valor());
      }
    }
    catch (Exception e)
    {
      e.printStackTrace();
      System.out.println("Funcional 3 PLP Parser Version 0.0.1:  Encountered errors during execution.");
    }
  }

  static final public Programa Input() throws ParseException {
    trace_call("Input");
    try {
Programa retorno;
      retorno = PPrograma();
      jj_consume_token(0);
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Input");
    }
}

  static final public ValorInteiro PValorInteiro() throws ParseException {
    trace_call("PValorInteiro");
    try {
Token token;
      token = jj_consume_token(INTEGER_LITERAL);
{if ("" != null) return new ValorInteiro(Integer.parseInt(token.toString()));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValorInteiro");
    }
}

  static final public ValorBooleano PValorBooleano() throws ParseException {
    trace_call("PValorBooleano");
    try {

      if (jj_2_1(2)) {
        jj_consume_token(FALSE);
{if ("" != null) return new ValorBooleano(false);}
      } else if (jj_2_2(2)) {
        jj_consume_token(TRUE);
{if ("" != null) return new ValorBooleano(true);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValorBooleano");
    }
}

  static final public ValorString PValorString() throws ParseException {
    trace_call("PValorString");
    try {
Token token;
      token = jj_consume_token(STRING_LITERAL);
String tokenStr = token.toString();
    tokenStr = tokenStr.substring(1, tokenStr.length() - 1);
    {if ("" != null) return new ValorString(tokenStr);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValorString");
    }
}

  static final public Valor PValorFuncao() throws ParseException {
    trace_call("PValorFuncao");
    try {
List lista = null;
  Expressao expressao;
      jj_consume_token(FN);
      lista = PListaId();
      jj_consume_token(DOT);
      expressao = PExpressao();
{if ("" != null) return new ValorFuncao(lista, expressao);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValorFuncao");
    }
}

  static final public Valor PValorLista() throws ParseException {
    trace_call("PValorLista");
    try {
Expressao v = null;
  ValorLista vlista = null;
      if (jj_2_4(2147483647)) {
        jj_consume_token(LBRACKET);
        jj_consume_token(RBRACKET);
{if ("" != null) return ValorLista.getInstancia(null, null);}
      } else if (jj_2_5(2)) {
        jj_consume_token(LBRACKET);
        v = PExpressao();
vlista = ValorLista.getInstancia(v, null);
        label_1:
        while (true) {
          if (jj_2_3(2)) {
            ;
          } else {
            break label_1;
          }
          jj_consume_token(COMMA);
          v = PExpressao();
vlista.cons(v);
        }
        jj_consume_token(RBRACKET);
{if ("" != null) return vlista.inverter();}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValorLista");
    }
}

  static final public Valor PValor() throws ParseException {
    trace_call("PValor");
    try {
Valor retorno;
      if (jj_2_6(2)) {
        retorno = PValorInteiro();
      } else if (jj_2_7(2)) {
        retorno = PValorBooleano();
      } else if (jj_2_8(2)) {
        retorno = PValorString();
      } else if (jj_2_9(2)) {
        retorno = PValorFuncao();
      } else if (jj_2_10(2)) {
        retorno = PValorLista();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PValor");
    }
}

  static final public Id PId() throws ParseException {
    trace_call("PId");
    try {
Token token;
      token = jj_consume_token(IDENTIFIER);
String tokenStr = token.toString();
    {if ("" != null) return new Id(tokenStr);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PId");
    }
}

  static final public Expressao PExpMenos() throws ParseException {
    trace_call("PExpMenos");
    try {
Expressao retorno;
      jj_consume_token(MINUS);
      retorno = PExpPrimaria();
{if ("" != null) return new ExpMenos(retorno);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpMenos");
    }
}

  static final public Expressao PExpNot() throws ParseException {
    trace_call("PExpNot");
    try {
Expressao retorno;
      jj_consume_token(NOT);
      retorno = PExpPrimaria();
{if ("" != null) return new ExpNot(retorno);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpNot");
    }
}

  static final public Expressao PExpLength() throws ParseException {
    trace_call("PExpLength");
    try {
Expressao retorno;
      jj_consume_token(LENGTH);
      retorno = PExpPrimaria();
if (retorno instanceof ValorString)
    {
      ValorString val = (ValorString) retorno;
    }
    {if ("" != null) return new ExpLength(retorno);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpLength");
    }
}

  static final public Expressao PExpPrimaria() throws ParseException {
    trace_call("PExpPrimaria");
    try {
Expressao retorno;
      if (jj_2_11(2)) {
        retorno = PValor();
      } else if (jj_2_12(2147483647)) {
        retorno = PAplicacao();
      } else if (jj_2_13(2)) {
        retorno = PId();
      } else if (jj_2_14(2)) {
        jj_consume_token(LPAREN);
        retorno = PExpressao();
        jj_consume_token(RPAREN);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpPrimaria");
    }
}

  static final public Expressao PAplicacao() throws ParseException {
    trace_call("PAplicacao");
    try {
Id id;
  List lista;
      id = PId();
      jj_consume_token(LPAREN);
      lista = PListaExpr();
      jj_consume_token(RPAREN);
{if ("" != null) return new Aplicacao(id, lista);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PAplicacao");
    }
}

  static final public List PListaExpr() throws ParseException {
    trace_call("PListaExpr");
    try {
List retorno = new ArrayList();
  Expressao e;
  boolean splat = false;
      if (jj_2_18(2)) {
        if (jj_2_15(2)) {
          jj_consume_token(STAR);
splat = true;
        } else {
          ;
        }
        e = PExpressao();
if (splat) {
          retorno.add(new ExpSplat(e));
          splat = false;
        } else {
          retorno.add(e);
        }
        label_2:
        while (true) {
          if (jj_2_16(2)) {
            ;
          } else {
            break label_2;
          }
          jj_consume_token(COMMA);
          if (jj_2_17(2)) {
            jj_consume_token(STAR);
splat = true;
          } else {
            ;
          }
          e = PExpressao();
if (splat) {
          retorno.add(new ExpSplat(e));
          splat = false;
        } else {
          retorno.add(e);
        }
        }
      } else {
        ;
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PListaExpr");
    }
}

  static final public List PListaId() throws ParseException {
    trace_call("PListaId");
    try {
List retorno = null;
  Id id;
      label_3:
      while (true) {
        if (jj_2_19(2)) {
          ;
        } else {
          break label_3;
        }
        id = PId();
if (retorno == null)
      {
        retorno = new ArrayList();
        retorno.add(id);
      }
      else
      {
        retorno.add(id);
      }
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PListaId");
    }
}

  static final public DeclaracaoFuncional PDeclVar() throws ParseException {
    trace_call("PDeclVar");
    try {
Id id;
  Expressao expressao;
  DeclaracaoFuncional retorno;
      jj_consume_token(VAR);
      id = PId();
      jj_consume_token(ASSIGN);
      expressao = PExpressao();
{if ("" != null) return new DecVariavel(id, expressao);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PDeclVar");
    }
}

  static final public DeclaracaoFuncional PDeclFuncao() throws ParseException {
    trace_call("PDeclFuncao");
    try {
Id id;
  Expressao expressao;
  DeclaracaoFuncional retorno;
  List lista;
      jj_consume_token(FUNC);
      id = PId();
      lista = PListaId();
      jj_consume_token(ASSIGN);
      expressao = PExpressao();
{if ("" != null) return new DecFuncao(id, new ValorFuncao(lista, expressao));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PDeclFuncao");
    }
}

  static final public DecComposta PDecComposta() throws ParseException {
    trace_call("PDecComposta");
    try {
DeclaracaoFuncional d1;
        DeclaracaoFuncional d2;
      if (jj_2_20(2)) {
        d1 = PDeclVar();
      } else if (jj_2_21(2)) {
        d1 = PDeclFuncao();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COMMA);
      d2 = PDeclFuncional();
{if ("" != null) return new DecComposta(d1, d2);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PDecComposta");
    }
}

  static final public DeclaracaoFuncional PDeclFuncional() throws ParseException {
    trace_call("PDeclFuncional");
    try {
DeclaracaoFuncional decl;
      if (jj_2_22(2147483647)) {
        decl = PDecComposta();
      } else if (jj_2_23(2147483647)) {
        decl = PDecComposta();
      } else if (jj_2_24(2)) {
        decl = PDeclVar();
      } else if (jj_2_25(2)) {
        decl = PDeclFuncao();
      } else if (jj_2_26(2)) {
        jj_consume_token(LPAREN);
        decl = PDeclFuncional();
        jj_consume_token(RPAREN);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return decl;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PDeclFuncional");
    }
}

  static final public Expressao PExpDeclaracao() throws ParseException {
    trace_call("PExpDeclaracao");
    try {
DeclaracaoFuncional  declaracoes;
  Expressao expressao;
      jj_consume_token(LET);
      declaracoes = PDeclFuncional();
      jj_consume_token(IN);
      expressao = PExpressao();
{if ("" != null) return new ExpDeclaracao(declaracoes, expressao);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpDeclaracao");
    }
}

  static final public Expressao PExpCondicional() throws ParseException {
    trace_call("PExpCondicional");
    try {
Expressao expCond, expThen, expElse;
      jj_consume_token(IF);
      expCond = PExpressao();
      jj_consume_token(THEN);
      expThen = PExpressao();
      jj_consume_token(ELSE);
      expElse = PExpressao();
{if ("" != null) return new IfThenElse(expCond, expThen, expElse);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpCondicional");
    }
}

  static final public Expressao PExpHead() throws ParseException {
    trace_call("PExpHead");
    try {
Expressao tmpExp = null;
      jj_consume_token(HEAD);
      tmpExp = PExpressao();
{if ("" != null) return new ExpHead(tmpExp);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpHead");
    }
}

  static final public Expressao PExpTail() throws ParseException {
    trace_call("PExpTail");
    try {
Expressao tmpExp = null;
      jj_consume_token(TAIL);
      tmpExp = PExpressao();
{if ("" != null) return new ExpTail(tmpExp);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpTail");
    }
}

  static final public Expressao PExpCompreensaoLista() throws ParseException {
    trace_call("PExpCompreensaoLista");
    try {
ExpCompreensaoLista retorno = null;
  Expressao expressao = null;
  Expressao filtro = null;
  List geradores = new ArrayList();
  Gerador geradorTemp = null;
      jj_consume_token(LBRACKET);
      expressao = PExpressao();
      label_4:
      while (true) {
        geradorTemp = PGerador();
geradores.add(geradorTemp);
        if (jj_2_27(2)) {
          ;
        } else {
          break label_4;
        }
      }
      if (jj_2_28(2)) {
        jj_consume_token(IF);
        filtro = PExpressao();
      } else {
        ;
      }
      jj_consume_token(RBRACKET);
retorno = new ExpCompreensaoLista(expressao);
    retorno.setFiltro(filtro);
    retorno.setGeradores(geradores);
    {if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpCompreensaoLista");
    }
}

  static final public Gerador PGerador() throws ParseException {
    trace_call("PGerador");
    try {
Id id = null;
  Expressao expressao = null;
      jj_consume_token(FOR);
      id = PId();
      jj_consume_token(IN);
      expressao = PExpressao();
      if (jj_2_29(2)) {
        jj_consume_token(COMMA);
      } else {
        ;
      }
{if ("" != null) return new Gerador(id, expressao);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PGerador");
    }
}

  static final public Expressao PExpUnaria() throws ParseException {
    trace_call("PExpUnaria");
    try {
Expressao retorno;
      if (jj_2_30(2147483647)) {
        retorno = PExpMenos();
      } else if (jj_2_31(2147483647)) {
        retorno = PExpNot();
      } else if (jj_2_32(2147483647)) {
        retorno = PExpLength();
      } else if (jj_2_33(2147483647)) {
        retorno = PExpHead();
      } else if (jj_2_34(2147483647)) {
        retorno = PExpTail();
      } else if (jj_2_35(2147483647)) {
        retorno = PExpDeclaracao();
      } else if (jj_2_36(2147483647)) {
        retorno = PExpCondicional();
      } else if (jj_2_37(2147483647)) {
        retorno = PExpCompreensaoLista();
      } else if (jj_2_38(2147483647)) {
        retorno = PExpPrimaria();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpUnaria");
    }
}

  static final public Expressao PExpBinaria() throws ParseException {
    trace_call("PExpBinaria");
    try {
Expressao retorno, param2;
  Id id;
  List list = null;
      retorno = PExpUnaria();
      label_5:
      while (true) {
        if (jj_2_39(2)) {
          ;
        } else {
          break label_5;
        }
        if (jj_2_40(2)) {
          jj_consume_token(PLUS);
          param2 = PExpUnaria();
retorno = new ExpSoma(retorno, param2);
        } else if (jj_2_41(2)) {
          jj_consume_token(MINUS);
          param2 = PExpUnaria();
retorno = new ExpSub(retorno, param2);
        } else if (jj_2_42(2)) {
          jj_consume_token(AND);
          param2 = PExpUnaria();
retorno = new ExpAnd(retorno, param2);
        } else if (jj_2_43(2)) {
          jj_consume_token(OR);
          param2 = PExpUnaria();
retorno = new ExpOr(retorno, param2);
        } else if (jj_2_44(2)) {
          jj_consume_token(EQ);
          param2 = PExpUnaria();
retorno = new ExpEquals(retorno, param2);
        } else if (jj_2_45(2)) {
          jj_consume_token(CONCAT);
          param2 = PExpUnaria();
retorno = new ExpConcat(retorno, param2);
        } else if (jj_2_46(2)) {
          jj_consume_token(CONS);
          param2 = PExpressao();
retorno = new ExpCons(retorno, param2);
        } else if (jj_2_47(2)) {
          jj_consume_token(CONCAT_LISTA);
          param2 = PExpressao();
retorno = new ExpConcatLista(retorno, param2);
        } else if (jj_2_48(2)) {
          jj_consume_token(SEQ);
          param2 = PExpressao();
retorno = new ExpSequencia(retorno, param2);
        } else if (jj_2_49(2)) {
          jj_consume_token(GT);
          param2 = PExpressao();
retorno = new ExpMaiorQue(retorno, param2);
        } else if (jj_2_50(2)) {
          jj_consume_token(LT);
          param2 = PExpressao();
retorno = new ExpMenorQue(retorno, param2);
        } else if (jj_2_51(2)) {
          jj_consume_token(STAR);
          param2 = PExpressao();
retorno = new ExpMult(retorno, param2);
        } else if (jj_2_52(2)) {
          jj_consume_token(LPAREN);
          list = PListaExpr();
          jj_consume_token(RPAREN);
retorno = new Aplicacao((Expressao) retorno, list);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpBinaria");
    }
}

  static final public Expressao PExpressao() throws ParseException {
    trace_call("PExpressao");
    try {
Expressao retorno;
      retorno = PExpBinaria();
{if ("" != null) return retorno;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PExpressao");
    }
}

  static final public Programa PPrograma() throws ParseException {
    trace_call("PPrograma");
    try {
Expressao retorno;
      retorno = PExpressao();
{if ("" != null) return new Programa(retorno);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("PPrograma");
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_16()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_17()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_18()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_19()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_20()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_21()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_22()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_23()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_24()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_25()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_26()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_27()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_28()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_29()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_30()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_31()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_32()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_33()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_34()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_35()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_36()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_2_37(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_37()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  static private boolean jj_2_38(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_38()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  static private boolean jj_2_39(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_39()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  static private boolean jj_2_40(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_40()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  static private boolean jj_2_41(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_41()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  static private boolean jj_2_42(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_42()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  static private boolean jj_2_43(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_43()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  static private boolean jj_2_44(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_44()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  static private boolean jj_2_45(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_45()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  static private boolean jj_2_46(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_46()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  static private boolean jj_2_47(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_47()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  static private boolean jj_2_48(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_48()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  static private boolean jj_2_49(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_49()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  static private boolean jj_2_50(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_50()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  static private boolean jj_2_51(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_51()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  static private boolean jj_2_52(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_52()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  static private boolean jj_3_38()
 {
    if (jj_3R_PExpPrimaria_477_3_26()) return true;
    return false;
  }

  static private boolean jj_3_37()
 {
    if (jj_3R_PExpCompreensaoLista_686_3_25()) return true;
    return false;
  }

  static private boolean jj_3_36()
 {
    if (jj_3R_PExpCondicional_646_3_24()) return true;
    return false;
  }

  static private boolean jj_3R_PValorFuncao_370_3_10()
 {
    if (jj_scan_token(FN)) return true;
    if (jj_3R_PListaId_546_3_30()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_35()
 {
    if (jj_3R_PExpDeclaracao_635_3_23()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_747_5_43()
 {
    if (jj_3R_PExpPrimaria_477_3_26()) return true;
    return false;
  }

  static private boolean jj_3_34()
 {
    if (jj_3R_PExpTail_671_3_22()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_744_5_42()
 {
    if (jj_3R_PExpCompreensaoLista_686_3_25()) return true;
    return false;
  }

  static private boolean jj_3_33()
 {
    if (jj_3R_PExpHead_660_3_21()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_741_5_41()
 {
    if (jj_3R_PExpCondicional_646_3_24()) return true;
    return false;
  }

  static private boolean jj_3_32()
 {
    if (jj_3R_PExpLength_462_3_20()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_738_5_40()
 {
    if (jj_3R_PExpDeclaracao_635_3_23()) return true;
    return false;
  }

  static private boolean jj_3_19()
 {
    if (jj_3R_PId_428_3_13()) return true;
    return false;
  }

  static private boolean jj_3R_PValorString_356_3_9()
 {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3_31()
 {
    if (jj_3R_PExpNot_451_3_19()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_735_5_39()
 {
    if (jj_3R_PExpTail_671_3_22()) return true;
    return false;
  }

  static private boolean jj_3R_PListaId_546_3_30()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_19()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_30()
 {
    if (jj_3R_PExpMenos_440_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_732_5_38()
 {
    if (jj_3R_PExpHead_660_3_21()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_729_5_37()
 {
    if (jj_3R_PExpLength_462_3_20()) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_726_5_36()
 {
    if (jj_3R_PExpNot_451_3_19()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_PExpUnaria_723_5_35()
 {
    if (jj_3R_PExpMenos_440_3_18()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_PValorBooleano_341_3_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PExpUnaria_722_3_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PExpUnaria_723_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_726_5_36()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_729_5_37()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_732_5_38()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_735_5_39()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_738_5_40()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_741_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_744_5_42()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpUnaria_747_5_43()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_17()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  static private boolean jj_3_16()
 {
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_17()) jj_scanpos = xsp;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PValorInteiro_331_3_7()
 {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_PGerador_711_3_17()
 {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_PId_428_3_13()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_29()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  static private boolean jj_3_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) jj_scanpos = xsp;
    if (jj_3R_PExpressao_842_3_6()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PListaExpr_508_3_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_28()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_27()
 {
    if (jj_3R_PGerador_711_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_PAplicacao_495_3_45()
 {
    if (jj_3R_PId_428_3_13()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_PListaExpr_508_3_28()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PExpCompreensaoLista_686_3_25()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    Token xsp;
    if (jj_3_27()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_27()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3_28()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_3R_PId_428_3_13()) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3_14()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_3R_PId_428_3_13()) return true;
    return false;
  }

  static private boolean jj_3R_PExpPrimaria_479_5_34()
 {
    if (jj_3R_PAplicacao_495_3_45()) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_PValor_411_3_12()) return true;
    return false;
  }

  static private boolean jj_3R_PExpTail_671_3_22()
 {
    if (jj_scan_token(TAIL)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PExpPrimaria_477_3_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_PExpPrimaria_479_5_34()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_PExpHead_660_3_21()
 {
    if (jj_scan_token(HEAD)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PExpLength_462_3_20()
 {
    if (jj_scan_token(LENGTH)) return true;
    if (jj_3R_PExpPrimaria_477_3_26()) return true;
    return false;
  }

  static private boolean jj_3R_PExpressao_842_3_6()
 {
    if (jj_3R_PExpBinaria_762_3_29()) return true;
    return false;
  }

  static private boolean jj_3R_PExpCondicional_646_3_24()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    if (jj_scan_token(THEN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PExpNot_451_3_19()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_PExpPrimaria_477_3_26()) return true;
    return false;
  }

  static private boolean jj_3_52()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_PListaExpr_508_3_28()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PExpDeclaracao_635_3_23()
 {
    if (jj_scan_token(LET)) return true;
    if (jj_3R_PDeclFuncional_615_3_16()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_51()
 {
    if (jj_scan_token(STAR)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PExpMenos_440_3_18()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_PExpPrimaria_477_3_26()) return true;
    return false;
  }

  static private boolean jj_3_23()
 {
    if (jj_3R_PDeclFuncao_588_3_15()) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  static private boolean jj_3_22()
 {
    if (jj_3R_PDeclVar_572_3_14()) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  static private boolean jj_3_50()
 {
    if (jj_scan_token(LT)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_26()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_PDeclFuncional_615_3_16()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_25()
 {
    if (jj_3R_PDeclFuncao_588_3_15()) return true;
    return false;
  }

  static private boolean jj_3_49()
 {
    if (jj_scan_token(GT)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_24()
 {
    if (jj_3R_PDeclVar_572_3_14()) return true;
    return false;
  }

  static private boolean jj_3R_PDeclFuncional_618_5_33()
 {
    if (jj_3R_PDecComposta_602_9_44()) return true;
    return false;
  }

  static private boolean jj_3R_PId_428_3_13()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_PDeclFuncional_616_5_32()
 {
    if (jj_3R_PDecComposta_602_9_44()) return true;
    return false;
  }

  static private boolean jj_3_48()
 {
    if (jj_scan_token(SEQ)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PDeclFuncional_615_3_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PDeclFuncional_616_5_32()) {
    jj_scanpos = xsp;
    if (jj_3R_PDeclFuncional_618_5_33()) {
    jj_scanpos = xsp;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_47()
 {
    if (jj_scan_token(CONCAT_LISTA)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_21()
 {
    if (jj_3R_PDeclFuncao_588_3_15()) return true;
    return false;
  }

  static private boolean jj_3_20()
 {
    if (jj_3R_PDeclVar_572_3_14()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_PValorLista_382_3_11()) return true;
    return false;
  }

  static private boolean jj_3R_PDecComposta_602_9_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) return true;
    }
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_PDeclFuncional_615_3_16()) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_PValorFuncao_370_3_10()) return true;
    return false;
  }

  static private boolean jj_3_46()
 {
    if (jj_scan_token(CONS)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_PValorString_356_3_9()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_PValorBooleano_341_3_8()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_PValorInteiro_331_3_7()) return true;
    return false;
  }

  static private boolean jj_3_45()
 {
    if (jj_scan_token(CONCAT)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3R_PValor_411_3_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_44()
 {
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3_43()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3R_PDeclFuncao_588_3_15()
 {
    if (jj_scan_token(FUNC)) return true;
    if (jj_3R_PId_428_3_13()) return true;
    if (jj_3R_PListaId_546_3_30()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_42()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3_41()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_3()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) {
    jj_scanpos = xsp;
    if (jj_3_45()) {
    jj_scanpos = xsp;
    if (jj_3_46()) {
    jj_scanpos = xsp;
    if (jj_3_47()) {
    jj_scanpos = xsp;
    if (jj_3_48()) {
    jj_scanpos = xsp;
    if (jj_3_49()) {
    jj_scanpos = xsp;
    if (jj_3_50()) {
    jj_scanpos = xsp;
    if (jj_3_51()) {
    jj_scanpos = xsp;
    if (jj_3_52()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_40()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    return false;
  }

  static private boolean jj_3R_PValorLista_382_3_31()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_PValorLista_382_3_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PValorLista_382_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_5()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PDeclVar_572_3_14()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_PId_428_3_13()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_PExpressao_842_3_6()) return true;
    return false;
  }

  static private boolean jj_3_29()
 {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  static private boolean jj_3R_PExpBinaria_762_3_29()
 {
    if (jj_3R_PExpUnaria_722_3_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public Func3ParserTokenManager token_source;
  static JavaCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[52];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public Func3Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Func3Parser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new Func3ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Func3Parser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new JavaCharStream(stream, 1, 1);
	 token_source = new Func3ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new JavaCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new Func3ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Func3Parser(Func3ParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(Func3ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[67];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 67; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  static private int trace_indent = 0;
/** Enable tracing. */
  static final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
	 trace_enabled = false;
  }

  static protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  static protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  static protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  static protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 52; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			   case 14: jj_3_15(); break;
			   case 15: jj_3_16(); break;
			   case 16: jj_3_17(); break;
			   case 17: jj_3_18(); break;
			   case 18: jj_3_19(); break;
			   case 19: jj_3_20(); break;
			   case 20: jj_3_21(); break;
			   case 21: jj_3_22(); break;
			   case 22: jj_3_23(); break;
			   case 23: jj_3_24(); break;
			   case 24: jj_3_25(); break;
			   case 25: jj_3_26(); break;
			   case 26: jj_3_27(); break;
			   case 27: jj_3_28(); break;
			   case 28: jj_3_29(); break;
			   case 29: jj_3_30(); break;
			   case 30: jj_3_31(); break;
			   case 31: jj_3_32(); break;
			   case 32: jj_3_33(); break;
			   case 33: jj_3_34(); break;
			   case 34: jj_3_35(); break;
			   case 35: jj_3_36(); break;
			   case 36: jj_3_37(); break;
			   case 37: jj_3_38(); break;
			   case 38: jj_3_39(); break;
			   case 39: jj_3_40(); break;
			   case 40: jj_3_41(); break;
			   case 41: jj_3_42(); break;
			   case 42: jj_3_43(); break;
			   case 43: jj_3_44(); break;
			   case 44: jj_3_45(); break;
			   case 45: jj_3_46(); break;
			   case 46: jj_3_47(); break;
			   case 47: jj_3_48(); break;
			   case 48: jj_3_49(); break;
			   case 49: jj_3_50(); break;
			   case 50: jj_3_51(); break;
			   case 51: jj_3_52(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
